// Indonesian administrative regions — the 38 provinces and every kota /
// kabupaten under them, used by the "Domisili" suggestion dropdown on the
// creator profile form. Kept as plain data (no API call) so the field works
// offline and the list can't shift under an existing profile.

export type Province = {
  province: string;
  kota: string[];
  kabupaten: string[];
};

export const INDONESIA_REGIONS: Province[] = [
  {
    province: "Aceh",
    kota: ["Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Subulussalam"],
    kabupaten: [
      "Aceh Barat",
      "Aceh Barat Daya",
      "Aceh Besar",
      "Aceh Jaya",
      "Aceh Selatan",
      "Aceh Singkil",
      "Aceh Tamiang",
      "Aceh Tengah",
      "Aceh Tenggara",
      "Aceh Timur",
      "Aceh Utara",
      "Bener Meriah",
      "Bireuen",
      "Gayo Lues",
      "Nagan Raya",
      "Pidie",
      "Pidie Jaya",
      "Simeulue",
    ],
  },
  {
    province: "Sumatera Utara",
    kota: [
      "Medan",
      "Binjai",
      "Gunungsitoli",
      "Padangsidimpuan",
      "Pematangsiantar",
      "Sibolga",
      "Tanjungbalai",
      "Tebing Tinggi",
    ],
    kabupaten: [
      "Asahan",
      "Batu Bara",
      "Dairi",
      "Deli Serdang",
      "Humbang Hasundutan",
      "Karo",
      "Labuhanbatu",
      "Labuhanbatu Selatan",
      "Labuhanbatu Utara",
      "Langkat",
      "Mandailing Natal",
      "Nias",
      "Nias Barat",
      "Nias Selatan",
      "Nias Utara",
      "Padang Lawas",
      "Padang Lawas Utara",
      "Pakpak Bharat",
      "Samosir",
      "Serdang Bedagai",
      "Simalungun",
      "Tapanuli Selatan",
      "Tapanuli Tengah",
      "Tapanuli Utara",
      "Toba",
    ],
  },
  {
    province: "Sumatera Barat",
    kota: [
      "Padang",
      "Bukittinggi",
      "Padang Panjang",
      "Pariaman",
      "Payakumbuh",
      "Sawahlunto",
      "Solok",
    ],
    kabupaten: [
      "Agam",
      "Dharmasraya",
      "Kepulauan Mentawai",
      "Lima Puluh Kota",
      "Padang Pariaman",
      "Pasaman",
      "Pasaman Barat",
      "Pesisir Selatan",
      "Sijunjung",
      "Solok",
      "Solok Selatan",
      "Tanah Datar",
    ],
  },
  {
    province: "Riau",
    kota: ["Pekanbaru", "Dumai"],
    kabupaten: [
      "Bengkalis",
      "Indragiri Hilir",
      "Indragiri Hulu",
      "Kampar",
      "Kepulauan Meranti",
      "Kuantan Singingi",
      "Pelalawan",
      "Rokan Hilir",
      "Rokan Hulu",
      "Siak",
    ],
  },
  {
    province: "Kepulauan Riau",
    kota: ["Batam", "Tanjungpinang"],
    kabupaten: ["Bintan", "Karimun", "Kepulauan Anambas", "Lingga", "Natuna"],
  },
  {
    province: "Jambi",
    kota: ["Jambi", "Sungai Penuh"],
    kabupaten: [
      "Batanghari",
      "Bungo",
      "Kerinci",
      "Merangin",
      "Muaro Jambi",
      "Sarolangun",
      "Tanjung Jabung Barat",
      "Tanjung Jabung Timur",
      "Tebo",
    ],
  },
  {
    province: "Sumatera Selatan",
    kota: ["Palembang", "Lubuklinggau", "Pagar Alam", "Prabumulih"],
    kabupaten: [
      "Banyuasin",
      "Empat Lawang",
      "Lahat",
      "Muara Enim",
      "Musi Banyuasin",
      "Musi Rawas",
      "Musi Rawas Utara",
      "Ogan Ilir",
      "Ogan Komering Ilir",
      "Ogan Komering Ulu",
      "Ogan Komering Ulu Selatan",
      "Ogan Komering Ulu Timur",
      "Penukal Abab Lematang Ilir",
    ],
  },
  {
    province: "Bengkulu",
    kota: ["Bengkulu"],
    kabupaten: [
      "Bengkulu Selatan",
      "Bengkulu Tengah",
      "Bengkulu Utara",
      "Kaur",
      "Kepahiang",
      "Lebong",
      "Mukomuko",
      "Rejang Lebong",
      "Seluma",
    ],
  },
  {
    province: "Lampung",
    kota: ["Bandar Lampung", "Metro"],
    kabupaten: [
      "Lampung Barat",
      "Lampung Selatan",
      "Lampung Tengah",
      "Lampung Timur",
      "Lampung Utara",
      "Mesuji",
      "Pesawaran",
      "Pesisir Barat",
      "Pringsewu",
      "Tanggamus",
      "Tulang Bawang",
      "Tulang Bawang Barat",
      "Way Kanan",
    ],
  },
  {
    province: "Kepulauan Bangka Belitung",
    kota: ["Pangkalpinang"],
    kabupaten: [
      "Bangka",
      "Bangka Barat",
      "Bangka Selatan",
      "Bangka Tengah",
      "Belitung",
      "Belitung Timur",
    ],
  },
  {
    province: "DKI Jakarta",
    kota: [
      "Jakarta Pusat",
      "Jakarta Utara",
      "Jakarta Barat",
      "Jakarta Selatan",
      "Jakarta Timur",
    ],
    kabupaten: ["Kepulauan Seribu"],
  },
  {
    province: "Jawa Barat",
    kota: [
      "Bandung",
      "Banjar",
      "Bekasi",
      "Bogor",
      "Cimahi",
      "Cirebon",
      "Depok",
      "Sukabumi",
      "Tasikmalaya",
    ],
    kabupaten: [
      "Bandung",
      "Bandung Barat",
      "Bekasi",
      "Bogor",
      "Ciamis",
      "Cianjur",
      "Cirebon",
      "Garut",
      "Indramayu",
      "Karawang",
      "Kuningan",
      "Majalengka",
      "Pangandaran",
      "Purwakarta",
      "Subang",
      "Sukabumi",
      "Sumedang",
      "Tasikmalaya",
    ],
  },
  {
    province: "Banten",
    kota: ["Serang", "Cilegon", "Tangerang", "Tangerang Selatan"],
    kabupaten: ["Lebak", "Pandeglang", "Serang", "Tangerang"],
  },
  {
    province: "Jawa Tengah",
    kota: [
      "Semarang",
      "Magelang",
      "Pekalongan",
      "Salatiga",
      "Surakarta",
      "Tegal",
    ],
    kabupaten: [
      "Banjarnegara",
      "Banyumas",
      "Batang",
      "Blora",
      "Boyolali",
      "Brebes",
      "Cilacap",
      "Demak",
      "Grobogan",
      "Jepara",
      "Karanganyar",
      "Kebumen",
      "Kendal",
      "Klaten",
      "Kudus",
      "Magelang",
      "Pati",
      "Pekalongan",
      "Pemalang",
      "Purbalingga",
      "Purworejo",
      "Rembang",
      "Semarang",
      "Sragen",
      "Sukoharjo",
      "Tegal",
      "Temanggung",
      "Wonogiri",
      "Wonosobo",
    ],
  },
  {
    province: "DI Yogyakarta",
    kota: ["Yogyakarta"],
    kabupaten: ["Bantul", "Gunungkidul", "Kulon Progo", "Sleman"],
  },
  {
    province: "Jawa Timur",
    kota: [
      "Surabaya",
      "Batu",
      "Blitar",
      "Kediri",
      "Madiun",
      "Malang",
      "Mojokerto",
      "Pasuruan",
      "Probolinggo",
    ],
    kabupaten: [
      "Bangkalan",
      "Banyuwangi",
      "Blitar",
      "Bojonegoro",
      "Bondowoso",
      "Gresik",
      "Jember",
      "Jombang",
      "Kediri",
      "Lamongan",
      "Lumajang",
      "Madiun",
      "Magetan",
      "Malang",
      "Mojokerto",
      "Nganjuk",
      "Ngawi",
      "Pacitan",
      "Pamekasan",
      "Pasuruan",
      "Ponorogo",
      "Probolinggo",
      "Sampang",
      "Sidoarjo",
      "Situbondo",
      "Sumenep",
      "Trenggalek",
      "Tuban",
      "Tulungagung",
    ],
  },
  {
    province: "Bali",
    kota: ["Denpasar"],
    kabupaten: [
      "Badung",
      "Bangli",
      "Buleleng",
      "Gianyar",
      "Jembrana",
      "Karangasem",
      "Klungkung",
      "Tabanan",
    ],
  },
  {
    province: "Nusa Tenggara Barat",
    kota: ["Mataram", "Bima"],
    kabupaten: [
      "Bima",
      "Dompu",
      "Lombok Barat",
      "Lombok Tengah",
      "Lombok Timur",
      "Lombok Utara",
      "Sumbawa",
      "Sumbawa Barat",
    ],
  },
  {
    province: "Nusa Tenggara Timur",
    kota: ["Kupang"],
    kabupaten: [
      "Alor",
      "Belu",
      "Ende",
      "Flores Timur",
      "Kupang",
      "Lembata",
      "Malaka",
      "Manggarai",
      "Manggarai Barat",
      "Manggarai Timur",
      "Nagekeo",
      "Ngada",
      "Rote Ndao",
      "Sabu Raijua",
      "Sikka",
      "Sumba Barat",
      "Sumba Barat Daya",
      "Sumba Tengah",
      "Sumba Timur",
      "Timor Tengah Selatan",
      "Timor Tengah Utara",
    ],
  },
  {
    province: "Kalimantan Barat",
    kota: ["Pontianak", "Singkawang"],
    kabupaten: [
      "Bengkayang",
      "Kapuas Hulu",
      "Kayong Utara",
      "Ketapang",
      "Kubu Raya",
      "Landak",
      "Melawi",
      "Mempawah",
      "Sambas",
      "Sanggau",
      "Sekadau",
      "Sintang",
    ],
  },
  {
    province: "Kalimantan Tengah",
    kota: ["Palangka Raya"],
    kabupaten: [
      "Barito Selatan",
      "Barito Timur",
      "Barito Utara",
      "Gunung Mas",
      "Kapuas",
      "Katingan",
      "Kotawaringin Barat",
      "Kotawaringin Timur",
      "Lamandau",
      "Murung Raya",
      "Pulang Pisau",
      "Seruyan",
      "Sukamara",
    ],
  },
  {
    province: "Kalimantan Selatan",
    kota: ["Banjarmasin", "Banjarbaru"],
    kabupaten: [
      "Balangan",
      "Banjar",
      "Barito Kuala",
      "Hulu Sungai Selatan",
      "Hulu Sungai Tengah",
      "Hulu Sungai Utara",
      "Kotabaru",
      "Tabalong",
      "Tanah Bumbu",
      "Tanah Laut",
      "Tapin",
    ],
  },
  {
    province: "Kalimantan Timur",
    kota: ["Samarinda", "Balikpapan", "Bontang"],
    kabupaten: [
      "Berau",
      "Kutai Barat",
      "Kutai Kartanegara",
      "Kutai Timur",
      "Mahakam Ulu",
      "Paser",
      "Penajam Paser Utara",
    ],
  },
  {
    province: "Kalimantan Utara",
    kota: ["Tarakan"],
    kabupaten: ["Bulungan", "Malinau", "Nunukan", "Tana Tidung"],
  },
  {
    province: "Sulawesi Utara",
    kota: ["Manado", "Bitung", "Kotamobagu", "Tomohon"],
    kabupaten: [
      "Bolaang Mongondow",
      "Bolaang Mongondow Selatan",
      "Bolaang Mongondow Timur",
      "Bolaang Mongondow Utara",
      "Kepulauan Sangihe",
      "Kepulauan Siau Tagulandang Biaro",
      "Kepulauan Talaud",
      "Minahasa",
      "Minahasa Selatan",
      "Minahasa Tenggara",
      "Minahasa Utara",
    ],
  },
  {
    province: "Gorontalo",
    kota: ["Gorontalo"],
    kabupaten: [
      "Boalemo",
      "Bone Bolango",
      "Gorontalo",
      "Gorontalo Utara",
      "Pohuwato",
    ],
  },
  {
    province: "Sulawesi Tengah",
    kota: ["Palu"],
    kabupaten: [
      "Banggai",
      "Banggai Kepulauan",
      "Banggai Laut",
      "Buol",
      "Donggala",
      "Morowali",
      "Morowali Utara",
      "Parigi Moutong",
      "Poso",
      "Sigi",
      "Tojo Una-Una",
      "Tolitoli",
    ],
  },
  {
    province: "Sulawesi Barat",
    kota: [],
    kabupaten: [
      "Majene",
      "Mamasa",
      "Mamuju",
      "Mamuju Tengah",
      "Pasangkayu",
      "Polewali Mandar",
    ],
  },
  {
    province: "Sulawesi Selatan",
    kota: ["Makassar", "Palopo", "Parepare"],
    kabupaten: [
      "Bantaeng",
      "Barru",
      "Bone",
      "Bulukumba",
      "Enrekang",
      "Gowa",
      "Jeneponto",
      "Kepulauan Selayar",
      "Luwu",
      "Luwu Timur",
      "Luwu Utara",
      "Maros",
      "Pangkajene dan Kepulauan",
      "Pinrang",
      "Sidenreng Rappang",
      "Sinjai",
      "Soppeng",
      "Takalar",
      "Tana Toraja",
      "Toraja Utara",
      "Wajo",
    ],
  },
  {
    province: "Sulawesi Tenggara",
    kota: ["Kendari", "Baubau"],
    kabupaten: [
      "Bombana",
      "Buton",
      "Buton Selatan",
      "Buton Tengah",
      "Buton Utara",
      "Kolaka",
      "Kolaka Timur",
      "Kolaka Utara",
      "Konawe",
      "Konawe Kepulauan",
      "Konawe Selatan",
      "Konawe Utara",
      "Muna",
      "Muna Barat",
      "Wakatobi",
    ],
  },
  {
    province: "Maluku",
    kota: ["Ambon", "Tual"],
    kabupaten: [
      "Buru",
      "Buru Selatan",
      "Kepulauan Aru",
      "Kepulauan Tanimbar",
      "Maluku Barat Daya",
      "Maluku Tengah",
      "Maluku Tenggara",
      "Seram Bagian Barat",
      "Seram Bagian Timur",
    ],
  },
  {
    province: "Maluku Utara",
    kota: ["Ternate", "Tidore Kepulauan"],
    kabupaten: [
      "Halmahera Barat",
      "Halmahera Selatan",
      "Halmahera Tengah",
      "Halmahera Timur",
      "Halmahera Utara",
      "Kepulauan Sula",
      "Pulau Morotai",
      "Pulau Taliabu",
    ],
  },
  {
    province: "Papua",
    kota: ["Jayapura"],
    kabupaten: [
      "Biak Numfor",
      "Jayapura",
      "Keerom",
      "Kepulauan Yapen",
      "Mamberamo Raya",
      "Sarmi",
      "Supiori",
      "Waropen",
    ],
  },
  {
    province: "Papua Barat",
    kota: [],
    kabupaten: [
      "Fakfak",
      "Kaimana",
      "Manokwari",
      "Manokwari Selatan",
      "Pegunungan Arfak",
      "Teluk Bintuni",
      "Teluk Wondama",
    ],
  },
  {
    province: "Papua Barat Daya",
    kota: ["Sorong"],
    kabupaten: ["Maybrat", "Raja Ampat", "Sorong", "Sorong Selatan", "Tambrauw"],
  },
  {
    province: "Papua Selatan",
    kota: [],
    kabupaten: ["Asmat", "Boven Digoel", "Mappi", "Merauke"],
  },
  {
    province: "Papua Tengah",
    kota: [],
    kabupaten: [
      "Deiyai",
      "Dogiyai",
      "Intan Jaya",
      "Mimika",
      "Nabire",
      "Paniai",
      "Puncak",
      "Puncak Jaya",
    ],
  },
  {
    province: "Papua Pegunungan",
    kota: [],
    kabupaten: [
      "Jayawijaya",
      "Lanny Jaya",
      "Mamberamo Tengah",
      "Nduga",
      "Pegunungan Bintang",
      "Tolikara",
      "Yahukimo",
      "Yalimo",
    ],
  },
];

export type Region = {
  /** What gets stored, e.g. "Kota Bandung, Jawa Barat". */
  label: string;
  /** Just the region, e.g. "Kota Bandung" — what the search matches first. */
  name: string;
  province: string;
};

// Flattened once at module load; both halves of the name are searchable, and a
// kota and its same-named kabupaten stay distinct entries.
export const INDONESIA_REGIONS_FLAT: Region[] = INDONESIA_REGIONS.flatMap((p) => [
  ...p.kota.map((k) => ({
    name: `Kota ${k}`,
    province: p.province,
    label: `Kota ${k}, ${p.province}`,
  })),
  ...p.kabupaten.map((k) => ({
    name: `Kab. ${k}`,
    province: p.province,
    label: `Kab. ${k}, ${p.province}`,
  })),
]);

// Case/whitespace-insensitive contains-match, name first then province, so
// typing "bandung" ranks the cities above everything in that province.
export function searchRegions(query: string, limit = 40): Region[] {
  const q = query.trim().toLowerCase();
  if (!q) return INDONESIA_REGIONS_FLAT.slice(0, limit);

  const starts: Region[] = [];
  const contains: Region[] = [];

  for (const r of INDONESIA_REGIONS_FLAT) {
    const name = r.name.toLowerCase();
    // Skip the "Kota "/"Kab. " prefix so typing the bare city name still hits.
    const bare = name.replace(/^(kota |kab\. )/, "");
    if (bare.startsWith(q) || name.startsWith(q)) starts.push(r);
    else if (name.includes(q) || r.province.toLowerCase().includes(q)) contains.push(r);
    if (starts.length >= limit) break;
  }

  return [...starts, ...contains].slice(0, limit);
}
